### ISSUE TITLE
Add File Summaries Functionality in Executor

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#115]
We need to add the ability for Executor to fetch file summaries of all the code files. This will aid agents in writing more efficient code.

- [x] Create file summaries and store them in a centrally shared place across multiple sessions. We can use Llama 3 8b for fetching summaries.
- [x] Use file summaries in the agent's system prompt.

**Comment by dakshbhardwaj** [comment]
Fixed by [#146](https://github.com/sirji-ai/sirji/pull/146)
