### ISSUE TITLE
Access to Folder Structure

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#122]
Provide folder structure info in agent's system prompt:
- [x] Read folder structure from TypeScript and set it in ENV variable (SIRJI_WORKSPACE_STRUCTURE) before invoking an agent.
- [x] Make the folder structure available in the system prompt of all agents.

READ_DIR_STRUCTURE has already been added as an action for Executor.

**Comment by dakshbhardwaj** [comment]
Fixed by [#146](https://github.com/sirji-ai/sirji/pull/146)
