### ISSUE TITLE
SHORTLISTER agent logic

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#133]
Following changes are needed in the SHORTLISTER logic:
- Move the finalization of files to Shortlister.
- Expose fetch dependencies as a capability of EXECUTOR. 2 types of files internally with SHORTLISTER - primary and dependency.
- Store the finalized files in shared resources.
- Read the problem statement from the shared resources.

**Comment by dakshbhardwaj** [comment]
Fixed by [#146](https://github.com/sirji-ai/sirji/pull/146)
