### ISSUE TITLE
Code Planner: new agent for step generation

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#134]
The new agent will have the following logic:
- Read the list of finalized files from shared resources.
- Read the content of those files.
- Generate detailed steps.
- Steps will have shortlisted file summaries.
- Get the steps finalized from the user.
- Store the finalized steps in shared resources.

**Comment by dakshbhardwaj** [comment]
Fixed by [#146](https://github.com/sirji-ai/sirji/pull/146)
