### ISSUE TITLE
The invoker agent must verify if relevant files are created by the invokee agent

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#135]
There will be an expectation block in the agent YAML file that lists down things the agent must save in shared resources. After getting a response from the agent, the invoker will check if these were created. If not created, it will again reply to the agent in the same session with findings and tell that the job is not done and it has wrongly reported that the job is done.

**Comment by dakshbhardwaj** [comment]
Fixed by [#146](https://github.com/sirji-ai/sirji/pull/146)
