### ISSUE TITLE
Build VS Code Extension

### ISSUE THREAD

**Issue by sunilkhedar** [sirji-ai/sirji#17]
## The problem to solve

Make Sirji more developer friendly.

## Proposed solution

Create a Visual Studio Code Extension that developers can use in their development environment, whether their local machine or a remote development environment.

Tasks:
- [x] Init VS Code extension package
- [x] Build a configuration interface where developers can add ENV variables required for Sirji and store them in secret storage
- [x] Prompt user to set up IDE workspace, if not selected
- [x] Create a Chat panel for devs to interact with Sirji
- [x] Write facilitator to allow communication between developer, agents, and tools
- [x] Python script to interact between Coding Agent (from sirji-agents package) and extension, also managing conversation history.
- [x] Python script to interact between Planning Agent (from sirji-agents package) and extension, also managing conversation history.
- [x] Python script to interact between Research Agent (from sirji-agents package) and extension, also managing conversation history.
- [x] Read SIRJI_WORKSPACE environment variable to create log files and crawler markdowns.
- [x] Spawning the Python scripts from Typescript code, passing the environment variables.
- [x] Write a util to interact with VS Code Editor to create, edit, and read files.
- [x] Write a util to interact with Terminal to execute code and install packages.
- [x] Write a util to interact with Browser to run web applications.
- [x] Verbose bot messages to users, including crucial updates.
- [x] Work on plan ui
- [x] Work on Settings ui
- [x] Publish Sirji on the marketplace.

**Comment by kedarchandrayan** [comment]
# Sirji VS Code Extension Architecture

The Sirji VS Code Extension (developed in TypeScript) provides an interactive chat interface right within Visual Studio Code IDE to assist the user in inputting their problem statement, submitting feedback or enhancement requests, and getting answers to various queries during the problem-solving process.

## Architecture Diagram
<img width="893" alt="vs code extension - architecture" src="https://github.com/sirji-ai/sirji/assets/7627517/6120d7cc-550c-4497-9d83-587bc2a8bc8a">

## Functionality
The extension leverages the capabilities of VS Code, such as:
- Editor
- Terminal
- Browser
- Project Explorer

Additionally, it introduces an Executor Agent built-in TypeScript that facilitates:
- Running Commands
- Filesystem Create, Read, Update, Delete (CRUD) operations
- Installing Packages

A chat interface is implemented within the VS Code IDE to interact with the user.

## PyPI Packages
To reuse code across multiple user interfaces (including the GUI of Dogfood, the VS Code Extension, and the future Browser interface), we have published these three PyPI packages:

### 1. **sirji-agents**
Implements three key agents:
- Coding Agent
- Planning Agent
- Research Agent

Utilizes:
- OpenAI Chat Completions API
- OpenAI Assistants API

This package communicates with models and RAG assistants.

### 2. **sirji-messages**
Covers:
- Message Factory
- Permissions Matrix (for defining message actions allowed between two agents)
- System prompt generation

### 3. **sirji-tools**
Provides tools for:
- Crawling (downloading web pages to markdown files)
- Searching (using the Google Search API for search results)
- Custom Logging

## Python Adapter Scripts
The Sirji VS Code Extension communicates with these Python packages via Python adapter scripts. These scripts are responsible for handling tasks like:
- Conversation history persistence
- Message formatting (when necessary)
