### ISSUE TITLE
Handling Unexpected Python Errors in Sirji by Opening Chat Interface

### ISSUE THREAD

**Issue by kedarchandrayan** [sirji-ai/sirji#31]
## Description
When Sirji encounters a Python error, it becomes unresponsive and locks users out of further interaction.

## Tasks
- [x] Upon catching a Python error, the error message is to be shown to the user in the chat.
- [x] The chat message box should be enabled upon catching a Python error.

**Comment by V-R-Dighe** [comment]
Update: Issue Resolved

The Python error-handling issue has been resolved. Now, when Sirji encounters a Python error:

- The error message will be displayed to the user in the chat.
- The chat message box will be enabled for further interaction.
